package integration

import io.kotest.core.annotation.Tags
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.nulls.shouldNotBeNull
import io.kotest.matchers.shouldBe
import io.kotest.matchers.types.shouldBeInstanceOf
import it.saabel.kotlinnotionclient.NotionClient
import it.saabel.kotlinnotionclient.config.NotionConfig
import it.saabel.kotlinnotionclient.models.base.Color
import it.saabel.kotlinnotionclient.models.base.Icon
import it.saabel.kotlinnotionclient.models.blocks.Block
import it.saabel.kotlinnotionclient.models.blocks.BlockAppendPosition
import it.saabel.kotlinnotionclient.models.blocks.BlockReference
import it.saabel.kotlinnotionclient.models.blocks.BlockRequest
import it.saabel.kotlinnotionclient.models.blocks.pageContent
import kotlinx.coroutines.delay

/**
 * Integration tests for all supported block types and the Content Creation DSL.
 *
 * Covers:
 * - Content DSL: all block types (headings, lists, tables, toggles, code, callouts, columns, etc.)
 * - Table blocks: simple, column-header, row-header, and both-header configurations
 * - Heading 4: colors, toggleable flag, rich text DSL
 * - Tab blocks: panes with and without icons
 * - Block append positions: Start, End, and AfterBlock insertion
 *
 * All sub-pages are created under a single container page. Trashing the container
 * (NOTION_CLEANUP_AFTER_TEST=true) cascades to all children.
 *
 * Prerequisites:
 * - export NOTION_API_TOKEN="secret_..."
 * - export NOTION_TEST_PAGE_ID="..."
 * - export NOTION_RUN_INTEGRATION_TESTS="true"
 *
 * Run with: ./gradlew integrationTest --tests "*BlockTypesIntegrationTest"
 */
@Tags("Integration", "RequiresApi")
class BlockTypesIntegrationTest :
    StringSpec({

        if (!integrationTestEnvVarsAreSet()) {
            "!(Skipped) block types integration" {
                println("Skipping BlockTypesIntegrationTest — set required env vars")
            }
        } else {
            val token = System.getenv("NOTION_API_TOKEN")
            val parentPageId = System.getenv("NOTION_TEST_PAGE_ID")
            val notion = NotionClient.create(NotionConfig(apiToken = token))

            var containerPageId = ""

            beforeSpec {
                val container =
                    notion.pages.create {
                        parent.page(parentPageId)
                        title("Block Types — Integration Tests")
                        icon.emoji("🧱")
                        content {
                            callout(
                                "ℹ️",
                                "This page is generated by the Kotlin Notion Client integration tests. " +
                                    "It demonstrates all supported block types and the Content Creation DSL. " +
                                    "Each sub-page below covers a specific area: the full DSL showcase, " +
                                    "table configurations, heading_4 variants, tab blocks, and block " +
                                    "append position behaviour.",
                            )
                        }
                    }
                containerPageId = container.id
                println("📄 Container: ${container.url}")
            }

            afterSpec {
                if (shouldCleanupAfterTest()) {
                    notion.pages.trash(containerPageId)
                    println("✅ Cleaned up container page (all children trashed)")
                } else {
                    println("🔧 Cleanup skipped — container page preserved for inspection")
                }
                notion.close()
            }

            // ------------------------------------------------------------------
            // 1. Content DSL — showcase of all block types
            // ------------------------------------------------------------------
            "should create a page with all DSL block types and verify them in Notion" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("Content DSL — All Block Types")
                        icon.emoji("🎨")
                        content {
                            callout("📖", "A self-contained showcase of every block type the Content DSL supports.")
                        }
                    }
                println("  DSL page: ${page.url}")
                delay(500)

                val blocks =
                    pageContent {
                        heading1("📚 Content DSL Showcase")
                        paragraph("Demonstrates every block type available through the Content Creation DSL.")
                        divider()
                        heading2("Text Blocks")
                        paragraph("A paragraph block.")
                        quote("A quote block.")
                        callout("💡", "A callout block.")
                        heading2("Lists")
                        bullet("Simple bullet")
                        bullet("Bullet with nested content") {
                            paragraph("Nested paragraph inside a bullet")
                            bullet("Nested bullet")
                        }
                        number("First numbered item")
                        number("Second numbered item") {
                            paragraph("Nested paragraph in numbered list")
                        }
                        toDo("Unchecked task", checked = false)
                        toDo("Checked task", checked = true)
                        heading2("Rich Content")
                        code(language = "kotlin", code = "val greeting = \"Hello!\"\nprintln(greeting)")
                        toggle("Click to expand") {
                            paragraph("Hidden content inside a toggle")
                            bullet("Nested list in toggle")
                        }
                        divider()
                        heading2("Layout")
                        columnList {
                            column {
                                paragraph("Left column")
                                bullet("Left bullet")
                            }
                            column {
                                paragraph("Right column")
                                bullet("Right bullet")
                            }
                        }
                        heading2("Embeds & Utilities")
                        bookmark("https://notion.so", caption = "Notion homepage")
                        embed("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
                        tableOfContents()
                        equation("E = mc^2")
                        breadcrumb()
                        divider()
                        paragraph("🎉 All block types demonstrated successfully.")
                    }

                val appendResponse = notion.blocks.appendChildren(page.id, blocks)
                appendResponse.objectType shouldBe "list"

                delay(1000)

                val retrieved = notion.blocks.retrieveChildren(page.id)
                // callout from create + all DSL blocks
                val dsBlocks = retrieved.drop(1) // skip the intro callout
                dsBlocks[0].shouldBeInstanceOf<Block.Heading1>()
                dsBlocks.filterIsInstance<Block.BulletedListItem>().size shouldBe 2
                dsBlocks.filterIsInstance<Block.NumberedListItem>().size shouldBe 2
                dsBlocks.filterIsInstance<Block.ToDo>().size shouldBe 2
                dsBlocks.filterIsInstance<Block.Code>().size shouldBe 1
                dsBlocks.filterIsInstance<Block.ColumnList>().size shouldBe 1
                dsBlocks.filterIsInstance<Block.Bookmark>().size shouldBe 1
                dsBlocks.filterIsInstance<Block.Embed>().size shouldBe 1
                dsBlocks.filterIsInstance<Block.Equation>().size shouldBe 1
                dsBlocks.filterIsInstance<Block.Breadcrumb>().size shouldBe 1

                println("  ✅ All block types verified in Notion")
            }

            // ------------------------------------------------------------------
            // 2. Table blocks — header configurations
            // ------------------------------------------------------------------
            "should create tables with various header configurations" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("Table Blocks — Header Configurations")
                        icon.emoji("📊")
                        content {
                            callout(
                                "📖",
                                "Demonstrates tables with no headers, column headers, row headers, " +
                                    "and both header types. Also includes a data table example.",
                            )
                        }
                    }
                println("  Table page: ${page.url}")
                delay(500)

                val tableBlocks =
                    pageContent {
                        heading2("Simple Table (no headers)")
                        table(tableWidth = 2, hasColumnHeader = false, hasRowHeader = false) {
                            row("Cell 1", "Cell 2")
                            row("Cell 3", "Cell 4")
                        }
                        heading2("Column Headers")
                        table(tableWidth = 3, hasColumnHeader = true, hasRowHeader = false) {
                            row("Name", "Age", "City")
                            row("Alice", "28", "Berlin")
                            row("Bob", "34", "London")
                        }
                        heading2("Row Headers")
                        table(tableWidth = 3, hasColumnHeader = false, hasRowHeader = true) {
                            row("Q1", "100", "200")
                            row("Q2", "150", "250")
                        }
                        heading2("Both Headers")
                        table(tableWidth = 4, hasColumnHeader = true, hasRowHeader = true) {
                            row("", "Product A", "Product B", "Product C")
                            row("Sales", "1000", "1500", "1200")
                            row("Returns", "50", "75", "60")
                        }
                        heading2("Data Table Example")
                        table(tableWidth = 4, hasColumnHeader = true, hasRowHeader = false) {
                            row("Month", "Revenue", "Costs", "Profit")
                            row("January", "€10,000", "€6,000", "€4,000")
                            row("February", "€12,000", "€6,500", "€5,500")
                            row("March", "€15,000", "€7,000", "€8,000")
                        }
                    }

                notion.blocks.appendChildren(page.id, tableBlocks)
                delay(1000)

                val retrieved = notion.blocks.retrieveChildren(page.id)
                val tables = retrieved.filterIsInstance<Block.Table>()
                tables shouldHaveSize 5

                // Verify structure of each table
                tables[0].table.tableWidth shouldBe 2
                tables[0].table.hasColumnHeader shouldBe false
                tables[0].table.hasRowHeader shouldBe false

                tables[1].table.tableWidth shouldBe 3
                tables[1].table.hasColumnHeader shouldBe true

                tables[2].table.hasRowHeader shouldBe true

                tables[3].table.hasColumnHeader shouldBe true
                tables[3].table.hasRowHeader shouldBe true

                // Verify row count and content for the simple table
                val simpleRows = notion.blocks.retrieveChildren(tables[0].id)
                simpleRows shouldHaveSize 2
                simpleRows.forEach { it.shouldBeInstanceOf<Block.TableRow>() }
                val firstRow = simpleRows[0] as Block.TableRow
                firstRow.tableRow.cells[0][0].plainText shouldBe "Cell 1"
                firstRow.tableRow.cells[1][0].plainText shouldBe "Cell 2"

                // Verify header row content for column-header table
                val colHeaderRows = notion.blocks.retrieveChildren(tables[1].id)
                val headerRow = colHeaderRows[0] as Block.TableRow
                headerRow.tableRow.cells[0][0].plainText shouldBe "Name"
                headerRow.tableRow.cells[1][0].plainText shouldBe "Age"

                println("  ✅ All table configurations verified in Notion")
            }

            // ------------------------------------------------------------------
            // 3. Heading 4 — colors, toggleable, rich text
            // ------------------------------------------------------------------
            "should create heading_4 blocks with color and toggle variants" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("Heading 4 — Colors, Toggle, Rich Text")
                        icon.emoji("🔤")
                        content {
                            callout(
                                "📖",
                                "Heading_4 is unique to the Notion API: it supports text color, " +
                                    "background color, the isToggleable flag, and rich text formatting.",
                            )
                        }
                    }
                println("  Heading4 page: ${page.url}")
                delay(500)

                notion.blocks.appendChildren(page.id) {
                    heading4("Plain heading_4")
                    heading4("Red text", color = Color.RED)
                    heading4("Blue background", color = Color.BLUE_BACKGROUND)
                    heading4("Toggleable heading", isToggleable = true)
                    heading4 {
                        italic("Italic")
                        text(" and plain text")
                    }
                }
                delay(1000)

                val retrieved = notion.blocks.retrieveChildren(page.id)
                val h4s = retrieved.drop(1).filterIsInstance<Block.Heading4>() // skip callout
                h4s shouldHaveSize 5

                h4s[0]
                    .heading4.richText
                    .first()
                    .plainText shouldBe "Plain heading_4"
                h4s[0].heading4.color shouldBe Color.DEFAULT
                h4s[0].heading4.isToggleable shouldBe false

                h4s[1].heading4.color shouldBe Color.RED
                h4s[2].heading4.color shouldBe Color.BLUE_BACKGROUND
                h4s[3].heading4.isToggleable shouldBe true

                h4s[4].heading4.richText shouldHaveSize 2
                h4s[4].heading4.richText[0].plainText shouldBe "Italic"
                h4s[4]
                    .heading4.richText[0]
                    .annotations.italic shouldBe true
                h4s[4].heading4.richText[1].plainText shouldBe " and plain text"
                h4s[4]
                    .heading4.richText[1]
                    .annotations.italic shouldBe false

                println("  ✅ All heading_4 variants verified in Notion")
            }

            // ------------------------------------------------------------------
            // 4. Tab blocks — panes with text and emoji icons
            // ------------------------------------------------------------------
            "should create a tab block with multiple panes and read it back" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("Tab Block — Panes and Icons")
                        icon.emoji("📑")
                        content {
                            callout(
                                "📖",
                                "Demonstrates the tab block type. Each pane is a paragraph block " +
                                    "that can carry its own label and optional icon.",
                            )
                            tab {
                                pane("Overview") {
                                    paragraph("The overview pane has no icon.")
                                }
                                pane(
                                    "Details",
                                    icon =
                                        it.saabel.kotlinnotionclient.models.blocks
                                            .emoji("📋"),
                                ) {
                                    paragraph("The details pane uses an emoji icon.")
                                    heading4("A sub-section inside Details")
                                }
                                pane(
                                    "Settings",
                                    icon =
                                        it.saabel.kotlinnotionclient.models.blocks
                                            .emoji("⚙️"),
                                ) {
                                    paragraph("The settings pane uses a different emoji icon.")
                                }
                            }
                        }
                    }
                println("  Tab page: ${page.url}")
                delay(500)

                val pageBlocks = notion.blocks.retrieveChildren(page.id)
                val tabBlock =
                    pageBlocks
                        .filterIsInstance<Block.Tab>()
                        .firstOrNull()
                        .shouldNotBeNull()

                tabBlock.type shouldBe "tab"
                tabBlock.hasChildren shouldBe true

                val panes = notion.blocks.retrieveChildren(tabBlock.id).filterIsInstance<Block.Paragraph>()
                panes shouldHaveSize 3

                panes[0]
                    .paragraph.richText
                    .first()
                    .plainText shouldBe "Overview"
                panes[0].paragraph.icon shouldBe null

                panes[1]
                    .paragraph.richText
                    .first()
                    .plainText shouldBe "Details"
                val pane2Icon = panes[1].paragraph.icon.shouldNotBeNull()
                (pane2Icon as? Icon.Emoji)?.emoji shouldBe "📋"

                panes[2]
                    .paragraph.richText
                    .first()
                    .plainText shouldBe "Settings"
                val pane3Icon = panes[2].paragraph.icon.shouldNotBeNull()
                (pane3Icon as? Icon.Emoji)?.emoji shouldBe "⚙️"

                println("  ✅ Tab block panes verified in Notion")
            }

            // ------------------------------------------------------------------
            // 5a. Block append position — Start
            // ------------------------------------------------------------------
            "should prepend blocks at Start position before existing content" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("Block Append — Start Position")
                        icon.emoji("⬆️")
                        content {
                            callout("📖", "Verifies that BlockAppendPosition.Start inserts content before existing blocks.")
                        }
                    }
                println("  Append-Start page: ${page.url}")
                delay(1000)

                notion.blocks.appendChildren(page.id) {
                    paragraph("Block A — initial first")
                    paragraph("Block B — initial second")
                }
                delay(1000)

                notion.blocks.appendChildren(page.id, position = BlockAppendPosition.Start) {
                    paragraph("Block PREPENDED — should appear before A and B")
                }
                delay(1000)

                val children = notion.blocks.retrieveChildren(page.id)
                // callout + 3 paragraphs = 4 blocks
                children.size shouldBe 4

                println("  ✅ Start position verified — prepended block is first after callout")
            }

            // ------------------------------------------------------------------
            // 5b. Block append position — AfterBlock
            // ------------------------------------------------------------------
            "should insert blocks at AfterBlock position after a specific block" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("Block Append — AfterBlock Position")
                        icon.emoji("↕️")
                        content {
                            callout(
                                "📖",
                                "Verifies that BlockAppendPosition.AfterBlock inserts content " +
                                    "immediately after the referenced block.",
                            )
                        }
                    }
                println("  Append-AfterBlock page: ${page.url}")
                delay(1000)

                notion.blocks.appendChildren(page.id) {
                    paragraph("Block A")
                    paragraph("Block B")
                    paragraph("Block C")
                }
                delay(1000)

                val initialChildren = notion.blocks.retrieveChildren(page.id)
                // callout + A + B + C = 4; paragraphs start at index 1
                val blockAId = initialChildren[1].id

                notion.blocks.appendChildren(
                    page.id,
                    position = BlockAppendPosition.AfterBlock(BlockReference(id = blockAId)),
                ) {
                    paragraph("Block AFTER_A — inserted between A and B")
                }
                delay(1000)

                val children = notion.blocks.retrieveChildren(page.id)
                // callout + A + AFTER_A + B + C = 5
                children.size shouldBe 5
                children[1].id shouldBe blockAId

                println("  ✅ AfterBlock position verified — inserted block follows Block A")
            }

            // ------------------------------------------------------------------
            // 5c. Block append position — End (explicit)
            // ------------------------------------------------------------------
            "should append blocks at End position after existing content" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("Block Append — End Position")
                        icon.emoji("⬇️")
                        content {
                            callout("📖", "Verifies that BlockAppendPosition.End (the default) appends content after all existing blocks.")
                        }
                    }
                println("  Append-End page: ${page.url}")
                delay(1000)

                notion.blocks.appendChildren(page.id) {
                    paragraph("Block A")
                    paragraph("Block B")
                }
                delay(1000)

                val initialChildren = notion.blocks.retrieveChildren(page.id)
                val lastBlockId = initialChildren.last().id

                notion.blocks.appendChildren(page.id, position = BlockAppendPosition.End) {
                    paragraph("Block APPENDED — should be last")
                }
                delay(1000)

                val children = notion.blocks.retrieveChildren(page.id)
                // callout + A + B + APPENDED = 4
                children.size shouldBe 4
                children[children.size - 2].id shouldBe lastBlockId

                println("  ✅ End position verified — appended block is last")
            }

            // ------------------------------------------------------------------
            // 5. retrieveChildrenFirstPage — single API call, no auto-pagination
            // ------------------------------------------------------------------
            "retrieveChildrenFirstPage should return exactly pageSize blocks and expose hasMore" {
                val page =
                    notion.pages.create {
                        parent.page(containerPageId)
                        title("retrieveChildrenFirstPage — Pagination Test")
                        icon.emoji("📄")
                        content {
                            callout("📖", "Verifies that retrieveChildrenFirstPage makes exactly one API call and exposes hasMore.")
                        }
                    }
                println("  First-page test page: ${page.url}")
                delay(1000)

                // Append 4 more paragraphs (page already has the callout = 1 block; total = 5)
                notion.blocks.appendChildren(page.id) {
                    paragraph("Block 1")
                    paragraph("Block 2")
                    paragraph("Block 3")
                    paragraph("Block 4")
                }
                delay(1000)

                // retrieveChildren() auto-paginates — should return all 5
                val all = notion.blocks.retrieveChildren(page.id)
                all.size shouldBe 5

                // retrieveChildrenFirstPage with pageSize=2 — exactly one API call
                val firstPage = notion.blocks.retrieveChildrenFirstPage(page.id, pageSize = 2)
                firstPage.results shouldHaveSize 2
                firstPage.hasMore shouldBe true
                firstPage.nextCursor.shouldNotBeNull()

                // Use the cursor manually to fetch the next page
                val secondPage =
                    notion.blocks.retrieveChildrenFirstPage(
                        page.id,
                        pageSize = 2,
                        startCursor = firstPage.nextCursor,
                    )
                secondPage.results shouldHaveSize 2
                secondPage.hasMore shouldBe true

                // Third page — last block
                val thirdPage =
                    notion.blocks.retrieveChildrenFirstPage(
                        page.id,
                        pageSize = 2,
                        startCursor = secondPage.nextCursor,
                    )
                thirdPage.results shouldHaveSize 1
                thirdPage.hasMore shouldBe false

                println(
                    "  ✅ retrieveChildrenFirstPage: page 1=${firstPage.results.size}, " +
                        "page 2=${secondPage.results.size}, page 3=${thirdPage.results.size} blocks " +
                        "(hasMore: ${firstPage.hasMore}, ${secondPage.hasMore}, ${thirdPage.hasMore})",
                )
            }
        }
    })
